title: Zach Nusbaum
baseurl: /
permalink: '/:title/'
palette: green
header:
  bg_img: images/header-bg.jpg
  has_nav: true
  has_social: true
  logo_img: images/logo.png
  tagline: San Diego Web Developer
  title: Zach Nusbaum
footer:
  content: '&copy; All rights reserved.'
  links:
    - new_window: true
      text: Made with Stackbit
      url: 'https://www.stackbit.com'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
